microservice-visualization:
  tags:
    "org.springframework.boot:spring-boot-dependencies": Spring Boot
    "org.springframework.cloud:spring-cloud-dependencies": Spring Cloud
    "org.springframework.boot:spring-boot-starter-web": MVC
    "org.springframework.boot:spring-boot-starter-amqp": RabbitMQ
    "org.springframework.boot:spring-boot-starter-data-mongodb": MongoDB
    "com.h2database:h2": H2
  projects:
    - name: Demo
      description: Demo description
      path-location: "result"
      application-postfix:
      application-api-postfix:
        - -api
      groups:
        - name: Group Demo
          description: Group Demo description
          application-names:
            - basket
            - ordering
      owners:
        - name: Team 1
          description: Team 1 - NY
          application-names:
            - basket
            - customer
        - name: Team 2
          description: Team 2 - TLV
          application-names:
            - product
            - ordering