spring:
  profiles:
    active: projects
  application:
    name: microservice-visualization
  datasource:
    url: jdbc:h2:mem:microservice_visualization
    #    url: jdbc:h2:file:./microservice_visualization_db
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  h2:
    console:
      path: /h2-console

  flyway:
    enabled: false

  output:
    ansi:
      enabled: always

logging:
  level:
    ROOT: info

server:
  port: 8080
